spring:
  application:
    name: orm
  datasource:
    url: jdbc:postgresql://localhost:5432/orm_demo
    username: postgres
    password: POSTGRES
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
